### ISSUE TITLE
Can not download from elasticsearch

### ISSUE THREAD

**Issue by zebozhuang** [tsaikd/golasticdump#7]
0 / 2800550 [--------------------------------------------------------------------------------------------------------]   0.00% 2s
Error: json: cannot unmarshal object into Go struct field SearchHits.hits.total of type int64

**Comment by zebozhuang** [comment]
> 0 / 2800550 [--------------------------------------------------------------------------------------------------------] 0.00% 2s Error: json: cannot unmarshal object into Go struct field SearchHits.hits.total of type int64

use `gopkg.in/olivere/elastic.v7` to support elk7

**Comment by tsaikd** [comment]
try https://github.com/tsaikd/golasticdump/tree/0.7.0

**Comment by zebozhuang** [comment]
> try https://github.com/tsaikd/golasticdump/tree/0.7.0

OK
